### ISSUE TITLE
Generate interesting examples

### ISSUE THREAD

**Issue by mhtess** [mhtess/comparison-class#2]
This will involve:
- A scalar adjective (e.g. tall, expensive, ...) [see linguistics papers for ideas]
- An entity (e.g. Bob)
- Information about the entity (bob is a giraffe, a 4 y.o.)

**Comment by lopez-brau** [comment]
**Sentences with vague adjectives**

Example 1:
- Scalar adjective(s): great, best, awful, worst
- Entity: Barack Obama (or any other president)
- Information about the entity: Barack Obama is the current President of the United States
- Usage: Barack Obama is the best/worst.
- Comparison class: other presidents

Example 2:
- Scalar adjective(s): heavy
- Entity: Beth
- Information about the entity: Beth is a cow
- Usage: Beth is heavy.
- Comparison class: other cows

Example 3:
- Scalar adjective(s): expensive, affordable
- Entity: The Affordable Care Act (ACA)
- Information about the entity: targeted to those who did not previously have health insurance due to income or other restrictions
- Usage: The ACA is too expensive.
- Comparison class: other ways of dealing with government-mandated health insurance or having none at all (purely privatized health insurance)

Example 4:
- Scalar adjective(s): strong
- Entity: Donnel
- Information about the entity: Donnel is a video game character
- Usage: Donnel is strong.
- Comparison class: other video game characters

Example 5:
- Scalar adjective(s): easy
- Entity: Jill
- Information about the entity: Jill is in the top 5% of her class
- Usage: Jill thought that the test was easy.
- Comparison class: other students in the top 5% of their class

Example 6:
- Scalar adjective(s): beautiful
- Entity: Anne
- Information about the entity: Anne is a little girl
- Usage: Anne is beautiful.
- Comparison class: other little girls

Example 7:
- Scalar adjective(s): vicious
- Entity: Pit bulls
- Information about the entity: Pit bulls were commonly used for dog-fighting (and still are, although illegally)
- Usage: Pit bulls are vicious.
- Comparison class: other breeds of dogs

Example 8:
- Scalar adjective(s): fast
- Entity: Usain Bolt
- Information about the entity: Usain Bolt is an Olympic track runner
- Usage: Usain bolt is fast.
- Comparison class: other track runners

Example 9:
- Scalar adjective(s): expensive, cheap
- Entity: The watch
- Information about the entity: N/A
- Usage: The watch is expensive.
- Comparison class: other watches, luxury items

**Comment by lopez-brau** [comment]
**Generic sentences**

Example 1:
- Adjective(s): terrorists
- Entity: Muslims
- Generic: Muslims are terrorists.
- Comparison class: people of other faiths

Example 2:
- Adjective(s): expensive, dangerous
- Entity: Tesla
- Generic: Teslas are expensive.
- Comparison class: other car brands

Example 3:
- Adjective(s): lazy, entitled
- Entity: Poor people 
- Usage: Poor people are lazy.
- Comparison class: other economic classes of people

Example 4:
- Adjective(s): power-hungry, corrupt, racist
- Entity: Police officers
- Usage: Police officers are racist.
- Comparison class: other professions

Example 5:
- Adjective(s): fat
- Entity: Americans
- Usage: Americans are fat.
- Comparison class: people of other nationalities 

Example 6:
- Adjective(s): scam
- Entity: Multi-level marketing companies
- Usage: Multi-level marketing companies are a scam.
- Comparison class: other business models

Example 7:
- Adjective(s): effective, ineffective
- Entity: Alternative medicine
- Usage: Alternative medicine is effective/ineffective.
- Comparison class: "Western" medicine

**Comment by lopez-brau** [comment]
Adjectives with measureable quantities:
- hot/cold (temperature)
- tall/short (height)
- expensive/cheap (price)
- heavy/light (weight)
- far/near (distance)
- long/short (duration)
